### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by zhoukaiwei66** [Zhouyuhao97/PLOME_finetune_pytorch#4]
您好，我微调过后，使用的时候需要将原来的pytorch_model.bin文件和保存的best_model.pth文件加载么，还是只需加载后者就行了？谢谢您

**Comment by Zhouyuhao97** [comment]
模型建立的时候应该可以只加载config

**Comment by zhoukaiwei66** [comment]
> 模型建立的时候应该可以只加载config，然后加载best_model.pth权重就行了

明白了，谢谢您！！
